import {
  nuggetSoEco1000,
  nuggetSoniceStik500,
  nuggetSoniceStik250,
  sosisGeboy500,
  cedeaFishRoll250,
  nuggetSoniceCoin250,
  nuggetSoniceCoin500,
  foodCraft1000,
  baksoVigo50,
} from "../assets/images";

export const daftarProduct = [
  {
    id: 1,
    kategori: "nugget",
    nama: "Sonice Stik 250gr",
    imgURL: nuggetSoniceStik250,
    harga: "Rp16.000",
    hargaFix: 16000,
    key: "soniceStik250",
    merk: "Sonice",
    kondisi: "Beku (-15°C - 0°C)",
    jenis: "Nugget",
    masaPenyimpanan: "12 Bulan",
    berat: "250GR",
    stok: 150,
  },

  {
    id: 2,
    kategori: "nugget",
    nama: "Sonice Coin 250gr",
    imgURL: nuggetSoniceCoin250,
    harga: "Rp16.000",
    hargaFix: 16000,
    key: "soniceCoin250",
    merk: "Sonice",
    kondisi: "Beku (-15°C - 0°C)",
    jenis: "Nugget",
    masaPenyimpanan: "12 Bulan",
    berat: "250GR",
    stok: 124,
  },
  {
    id: 3,
    kategori: "nugget",
    nama: "Sonice Stik 500gr",
    imgURL: nuggetSoniceStik500,
    harga: "Rp31.000",
    hargaFix: 31000,
    key: "soniceStik500",
    merk: "Sonice",
    kondisi: "Beku (-15°C - 0°C)",
    jenis: "Nugget",
    masaPenyimpanan: "12 Bulan",
    berat: "500GR",
    stok: 98,
  },
  {
    id: 4,
    kategori: "nugget",
    nama: "Sonice Coin 500gr",
    imgURL: nuggetSoniceCoin500,
    harga: "Rp31.000",
    hargaFix: 31000,
    key: "soniceCoin500",
    merk: "Sonice",
    kondisi: "Beku (-15°C - 0°C)",
    jenis: "Nugget",
    masaPenyimpanan: "12 Bulan",
    berat: "500GR",
    stok: 128,
  },
  {
    id: 5,
    kategori: "nugget",
    nama: "So Eco 1000gr",
    imgURL: nuggetSoEco1000,
    harga: "Rp35.000",
    hargaFix: 35000,
    key: "soEco1000",
    merk: "So Eco",
    kondisi: "Beku (-15°C - 0°C)",
    jenis: "Nugget",
    masaPenyimpanan: "12 Bulan",
    berat: "1000GR",
    stok: 228,
  },

  // Sosis
  {
    id: 6,
    kategori: "sosis",
    nama: "Geboyku 500gr",
    imgURL: sosisGeboy500,
    harga: "Rp18.000",
    hargaFix: 18000,
    key: "sosisGeboy500",
    merk: "Geboyku",
    kondisi: "Beku (-15°C - 0°C)",
    jenis: "Sosis",
    masaPenyimpanan: "12 Bulan",
    berat: "500GR",
    stok: 88,
  },

  // Lainnya
  {
    id: 7,
    kategori: "lainnya",
    nama: "Cedea Fishroll 250g",
    imgURL: cedeaFishRoll250,
    harga: "Rp16.000",
    hargaFix: 16000,
    key: "cedeaFishroll250",
    merk: "Cedea",
    kondisi: "Beku (-15°C - 0°C)",
    jenis: "Fish Roll",
    masaPenyimpanan: "12 Bulan",
    berat: "250GR",
    stok: 40,
  },
  {
    id: 8,
    kategori: "lainnya",
    nama: "Foodcraft 1000g",
    imgURL: foodCraft1000,
    harga: "Rp35.000",
    hargaFix: 35000,
    key: "kentangFoodcraft1000",
    merk: "Foodcraft",
    kondisi: "Beku (-15°C - 0°C)",
    jenis: "Kentang",
    masaPenyimpanan: "12 Bulan",
    berat: "1000GR",
    stok: 45,
  },
  {
    id: 9,
    kategori: "lainnya",
    nama: "Vigo 50butir",
    imgURL: baksoVigo50,
    harga: "Rp25.000",
    hargaFix: 25000,
    key: "basoVigo50",
    merk: "Vigo",
    kondisi: "Beku (-15°C - 0°C)",
    jenis: "Bakso",
    masaPenyimpanan: "12 Bulan",
    berat: "500GR",
    stok: 46,
  },
];
